[package]
name = "tlot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.12.1"
bevy_psx = { git="https://github.com/tajo48/bevy_psx.git" }
